typography_spectrum: 0.91586
color:
  brandColors:
    - '#fbf8c1'
    - '#2a221f'
    - '#01bfbd'
    - '#ff3146'
    - '#05747f'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.98936
analytics:
  google: UA-71524793-1
  facebook: null
  twitter: null
name: Percept Sequence
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Percept Sequence
description: 'AI, Medicine, Startups'
purpose: []
