name: Percept Sequence
favicon: null
layout_spectrum: 1
typography_spectrum: 0.91586
title: Percept Sequence
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71524793-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#50545f'
    - '#bdeefe'
    - '#29fa2e'
    - '#eac62c'
    - '#cf0814'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
